language: julia
os:
  - linux
julia:
  - 1.0
  - 1.1
  - 1.2
  - nightly
matrix:
  allow_failures:
    - julia: 1.0
    - julia: 1.2
    - julia: nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --project --code-coverage=tracefile-%p.info --code-coverage=user --eval 'using Pkg; Pkg.build(); Pkg.test(; coverage=true)';
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); import Codecov; Codecov.submit(Codecov.process_folder())'
jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
