language: julia
os:
  - linux
julia:
  - 1.0
  - 1.2
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
script:
  - bash build_and_test.sh
after_success:
  - bash coverage/coverage.sh
  - bash docs/document.sh
